# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle app source inside Docker image
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define environment variable
ENV PORT=3000
ENV CORS_ORIGIN=http://localhost:3001
ENV JWT_SECRET=your_jwt_secret_here
ENV EMAIL_USER=your_email_user_here
ENV EMAIL_PASSWORD=your_email_password_here

# Run app.py when the container launches
CMD ["node", "server.js"]
